# Serverless Pro account information
org: crash7
app: serverless-pro-ci-cd-test

service: api-bridge-gh

provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region}
  stage: ${opt:stage}
  apiGateway:
    shouldStartNameWithService: true
  environment:
    NODE_ENV: ${self:provider.stage}

functions:
  repositories:
    handler: lambda.retrieveUserInfo
    memorySize: 256
    timeout: 29
    environment:
      GH_TOKEN: ${param:GH_TOKEN}
    events:
      - http:
          path: /repos/{user}
          method: GET
          cors: true

custom:
  serverless-offline:
    httpPort: 4000
    noPrependStageInUrl: true

plugins:
  - serverless-offline
